apiVersion: v1
kind: ConfigMap
metadata:
  name: guam-message
data:
  index.html: |
    <h1 style="color:violet;">We are enjoy our holidays in Guam</h1>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-guam
  name: nginx-guam
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-guam
  template:
    metadata:
      labels:
        app: nginx-guam
    spec:
      containers:
      - image: nginx
        name: nginx
        volumeMounts:
          - name: guam-message-volume
            mountPath: /usr/share/nginx/html/
      volumes:
      - name: guam-message-volume
        configMap:
          name: guam-message
