apiVersion: v1
kind: Pod
metadata:
  name: tokyo-tower-sidecar-info
spec:
  containers:

    - name: info-of-the-day
      image: busybox
      command: ['sh', '-c', "echo '<h1>***** Tokyo Tower Will Be Opened On April, 1st ... And This Is Not A Joke! *****</h1>' > /tokyo/towaaaaa/info/index.html && tail -f /dev/null"]
      volumeMounts:
        - name: info-message
          mountPath: /tokyo/towaaaaa/info

    - name: nginx
      image: nginx
      volumeMounts:
        - name: info-message
          mountPath: /usr/share/nginx/html

  volumes:
    - name: info-message
      emptyDir: {}
