apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-scheduled-in-node-affinity-defined-by-pv-affinity
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 512Ki
  # if no storageClassName defined kubernetes assumes `Dynamic` type of provisioning so need to change the provisioner on StorageClass
  storageClassName: ""
  #storageClassName: local-storage
  #selector:
  #  matchLabels:
  #    release: "stable"
  #  matchExpressions:
  #    - {key: environment, operator: In, values: [dev]}

