apiVersion: v1
kind: ConfigMap
metadata:
  name: hawaii-message
data:
  index.html: |
    <h1 style="color:green;">We are enjoy our holidays in Hawaii</h1>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-hawaii
  name: nginx-hawaii
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-hawaii
  template:
    metadata:
      labels:
        app: nginx-hawaii
    spec:
      containers:
      - image: nginx
        name: nginx
        volumeMounts:
          - name: hawaii-message-volume
            mountPath: /usr/share/nginx/html/
      volumes:
      - name: hawaii-message-volume
        configMap:
          name: hawaii-message
