metadata:
  annotations:
    kubernetes.io/change-cause: "Shibuya is not accessible today, VIOLET ALERT!"
spec:
  template:
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - name: nginx-violet
          mountPath: /usr/share/nginx/html/
      volumes:
      - name: nginx-violet
        configMap:
          name: nginx-html
