# nginx-jiguoka-pod
apiVersion: v1
kind: Pod
metadata:
  name: nginx-standalone
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      image: nginx
  nodeSelector:
    location: jiguoka
