apiVersion: v1
kind: ConfigMap
metadata:
  name: <name of the config map in base>
data:
  index.html: |
    <h1 style="color:red">Yoyogi Park North Part Heading to Shinjuku Will Be Closed for Golden Weeks Festival Preparation.</h1>
