apiVersion: v1
kind: ConfigMap
metadata:
  # configMap name attached to the `deployment` in the 'base' and created by its `kustomize` `configMapGenerator`
  # this one will patch it
  name: yoyogi-announcement
data:
  index.html: |
    <h1 style="color:red">Yoyogi Park North Part Heading to Shinjuku Will Be Closed for Golden Weeks Festival Preparation.</h1>
