apiVersion: v1
kind: Namespace
metadata:
  name: yoyogi-park
---
apiVersion: v1
data:
  index.html: |
    <h1 style="color:violet">Very <strong>nostalgic</strong> Mood</h1>
kind: ConfigMap
metadata:
  name: html-mood
  namespace: yoyogi-park
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: golden-visitor
  name: golden-visitor-service
  namespace: yoyogi-park
spec:
  ports:
  - nodePort: 30088
    port: 80
    targetPort: 80
  selector:
    app: golden-visitor
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: golden-visitor
  name: golden-visitor
  namespace: yoyogi-park
spec:
  containers:
  - image: nginx
    name: golden-visitor
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: visitor-mood-volume
  volumes:
  - configMap:
      name: html-mood
    name: visitor-mood-volume
