prometheus:
  prometheusSpec:
    resources:
      requests:
        memory: "200Mi"
        cpu: "50m"
      limits:
        memory: "500Mi"
        cpu: "250m"
  service:
    type: NodePort
    nodePort: 30900


nodeExporter:
  resources:
    requests:
      memory: "100Mi"
      cpu: "50m"
    limits:
      memory: "200Mi"
      cpu: "100m"

grafana:
  service:
    type: NodePort
    nodePort: 32000 
