# install `kustomize` binary locally: `curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash`
# build with: `kustomize build . --enable-helm > helm_kustomize_deploy_prep.yaml`
# run with: `k apply -f helm_kustomize_deploy_prep.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# have to put this first as it going to apply changes following the order top to bottom
# and `namespace` need be present for the `helm prometheus stack` chart to be deployed there otherwise we will get error `namespace not there mate!`
resources:
- yoyogi-monitoring-namespace.yaml

# what is good here is that we don't need to install `helm` in our terminal `helmCharts` will take care of everything, pulling and releasing
#  but, NO HELM RELEASE possibility, this is the limitation of`kustomize-helm`, therefore, NO ROLLBACK
# just pulls repo and apply directly manifest to cluster with all defined in `helm chart`
helmCharts:
- name: yoyogi-vistor
  releaseName: yoyogi-visitor
  namespace: default
  repo: /home/creditizens/kubeadm_updating_cluster/kustomize/helm_kustomize/yoyogi-visitor
  version: 0.0.1
  valuesFile: custom-yoyogi-visitor-values.yaml
  includeCRDs: true

