apiVersion: v1
kind: LimitRange
metadata:
  name: meidaimae-default-cpu-container-level
  namespace: controlled-resources
spec:
  limits:
  # we focus on `CPU` but you can use this file to setup default for other resources like `memory` for eg.
  - default:
      cpu: "500m"
    defaultRequest:
      cpu: "500m"
    max:
      cpu: "750m"
    min:
      cpu: "200m"
    # type here can be pod/container for eg.
    type: Container

---
apiVersion: v1
kind: LimitRange
metadata:
  name: meidaimae-default-cpu-pod-level
  namespace: controlled-resources
spec:
  limits:
  # we focus on `CPU` but you can use this file to setup default for other resources like `memory` for eg.
  - type: Pod
    max:
      cpu: "2"
      memory: "2Gi"
