# nginx-jiguoka-standalone.yaml Pod
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx
  name: nginx-jiguoka-standalone
spec:
  containers:
  - image: nginx
    name: nginx
  nodeSelector:
    location: jiguoka
