apiVersion: batch/v1
kind: CronJob
metadata:
  name: shibuya-cronjob
spec:
  schedule: "*/1 * * * *"
  successfulJobsHistoryLimit: 50
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 120
      template:
        spec:
          containers:
          - name: hello
            image: busybox:1.36.1
            #imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - echo "<h1 style='display:flex;flex-direction:row;align-items:center;justify-content:center;color:darkblue;'>Junko will be here on the $(date | awk '{print $2,$3}') at $(date | awk '{print $4}')</h1>" > "/tmp/index.html"
            # - echo "junko will be here on the $(date)" > "/tmp/index.html"
            volumeMounts:
            - name: shared-volume
              mountPath: "/tmp"
          restartPolicy: OnFailure
          volumes:
          - name: shared-volume
            hostPath:
              path: "/tmp"
              #type: DirectoryOrCreate

          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: location
                    operator: In
                    values:
                    - shibuya
