apiVersion: v1
kind: Pod
metadata:
  labels:
    app: test-nginx
  name: test-nginx
spec:
  containers:
  - image: nginx
    name: test-nginx
    volumeMounts:
    - name: shared-volume
      mountPath: "/usr/share/nginx/html"

  volumes:
  - name: shared-volume
    hostPath:
      path: "/tmp"
      #type: DirectoryOrCreate

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: location
            operator: In
            values:
            - shibuya
