# ngin-noexecute-tolerated.yaml Pod NoExecute
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx-tolerate-noexecute
  name: nginx-no-toleration-second
spec:
  containers:
    - name: nginx-tolerate-noexecute
      image: nginx
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: junko
              operator: Exists
  tolerations:
    - { key: "shibuya", operator: "Equal", value: "present", effect: "NoExecute" }
