# nginx-noschedule-tolerated2.yaml Pod NoSchedule
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx-tolerate-noschedule
  name: nginx-noshedule2
spec:
  containers:
    - name: nginx-tolerate-noschedule
      image: nginx
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: junko
              operator: Exists
  tolerations:
    - { key: "ueno", operator: "Equal", value: "narita", effect: "PreferNoSchedule" }
