apiVersion: v1
kind: Pod
metadata:
  name: junko-time-present-reader
  # MSUT set a label
  labels:
    app: junko-time-reader-app
spec:

  containers:
  #############################################################################################
  - image: nginx
    name: shibuya-webpage-info
    volumeMounts:
    - name: shared-volume
      mountPath: "/usr/share/nginx/html"
    resources:
      limits:
        memory: 150Mi
        cpu: 250m
    ports:
    - containerPort: 9114
      name: shibuya-webpage-info-container-metrix

  #############################################################################################
  - name: nginx-exporter
    image: 'nginx/nginx-prometheus-exporter:0.10.0'
    args:
      - '-nginx.scrape-uri=http://localhost/nginx_status'
    resources:
      limits:
        memory: 150Mi
        cpu: 300m
    # MUST have por exposed
    ports:
    - containerPort: 9113
      name: nginx-exporter-container-metrix

  #############################################################################################
  # now the 'physical' `volume` on the `node` using `hostPath`
  volumes:
  - name: shared-volume
    hostPath:
    path: "/tmp/junko-timing"
    type: "DirectoryOrCreate"
