apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-3-with-mandatory-affinity-set
spec:
  capacity:
    storage: 512Ki
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: ""
  # storageClassName: local-storage
  local:
    path: /tmp/local-pv
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        # custom
        - key: location
          operator: Exists

