apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-following-node-affinity-defined-in-pv-with-or-without-storageclass
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 512Ki
  # if no storageClassName defined kubernetes assumes `Dynamic` type of provisioning so need to change the provisioner on StorageClass
  # storageClassName: ""
  # this is the rancher Dynamic provisioner
  storageClassName: local-path

  # `selector` can be defined with `matchLabels` and `matchExpressions`

