apiVersion: v1
kind: Pod
metadata:
  name: pod-needing-storage2
spec:
  containers:
    - name: i-need-storage-pod
      image: nginx
      volumeMounts:
      # here using mountpath
      - mountPath: "/tmp/local-pv"
        name: my-local-storage2
  volumes:
    - name: my-local-storage2
      persistentVolumeClaim:
        claimName: japan-pvc2

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - node1.creditizens.net
