apiVersion: v1
kind: Pod
metadata:
  name: pod-needing-storage-default
spec:
  containers:
    - name: i-need-storage-pod-default
      image: nginx
      volumeMounts:
      - mountPath: "/tmp/local-pv"
        name: my-local-storage
  volumes:
    - name: my-local-storage
      persistentVolumeClaim:
        claimName: default-japan-pvc

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - node2.creditizens.net

