apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: japan-pvc2
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 512Ki
  storageClassName: japan-storage2

