apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: default-japan-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 512Ki
  storageClassName: local-path

