apiVersion: v1
kind: ConfigMap
metadata:
  name: html-mood
data:
  index.html: |
    <h1 style="color:{{ .Values.htmlColor }}">Very <strong>{{ .Values.mood }}</strong> Mood</h1>

---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: golden-visitor
  name: golden-visitor
spec:
  containers:
  - name: golden-visitor
    image: nginx
    volumeMounts:
      - name: visitor-mood-volume
        mountPath: /usr/share/nginx/html

  volumes:
    - name: visitor-mood-volume
      configMap:
        name: html-mood

  # affinity:
# {{ toYaml .Values.affinity | indent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: golden-visitor-service
  labels:
    app: golden-visitor
spec:
  selector:
    app: golden-visitor
  type: NodePort
  ports:
  - nodePort: {{ .Values.nodePort }}
    port: 80
    targetPort: 80
