apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mangakissa-admissionfriend
  name: mangakissa-admission-3-friend
  namespace: mangakissa-zone
  annotations:
    creditizens-vip-friends: "naruto no soundo"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mangakissa-admission-friend
  template:
    metadata:
      labels:
        app: mangakissa-admission-friend
    spec:
      containers:
      - image: nginx
        name: nginx

